name: Build and Push to ECR

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Debug AWS
      run: aws sts get-caller-identity

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 123399119691.dkr.ecr.us-east-1.amazonaws.com

    - name: Build frontend
      run: |
        docker build -t frontend ./frontend
        docker tag frontend:latest 123399119691.dkr.ecr.us-east-1.amazonaws.com/frontend:latest

    - name: Push frontend
      run: docker push 123399119691.dkr.ecr.us-east-1.amazonaws.com/frontend:latest

    - name: Build backend
      run: |
        docker build -t backend ./backend
        docker tag backend:latest 123399119691.dkr.ecr.us-east-1.amazonaws.com/backend:latest

    - name: Push backend
      run: docker push 123399119691.dkr.ecr.us-east-1.amazonaws.com/backend:latest
